"""Initial migration.

Revision ID: 1dfa1f4a4d0f
Revises: 
Create Date: 2024-05-31 23:16:49.342164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dfa1f4a4d0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('agencia', sa.String(length=6), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('bloqueada', sa.Boolean(), nullable=True),
    sa.Column('portador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portador_id'], ['portador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conta')
    op.drop_table('portador')
    # ### end Alembic commands ###
